FROM ghcr.io/foundry-rs/foundry

WORKDIR /develop
COPY . .

RUN forge b --skip test
CMD ["forge script script/DeploySetup.s.sol:DeploySetup \
    -f http://anvil:8545 \
    --broadcast \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"]
